### ISSUE TITLE
How to remove tray icon after showing message

### ISSUE THREAD

**Issue by AmirAli-AZ** [dustinkredmond/FXTrayIcon#34] opened 2022-01-06 13:42 UTC
I'm trying to remove tray icon after showing message using this code :
```java
private void showNotification(String title, String message, MessageType type) {
        if (FXTrayIcon.isSupported()) {
            FXTrayIcon notification = new FXTrayIcon((Stage) container.getScene().getWindow(), DownloaderUIController.class.getResource("icons/icon.png"));
            notification.show();
            switch (type) {
                case INFO -> notification.showInfoMessage(title, message);
                case WARNING -> notification.showWarningMessage(title, message);
                case ERROR -> notification.showErrorMessage(title, message);
            }
            notification.clear();
        }
    }

    private enum MessageType {
        INFO, WARNING, ERROR
    }
```
but there is still
also I'm using **windows 10**

**Comment by dustinkredmond** [comment] 2022-01-07 00:10
Hi @AmirAli-AZ, if you want to remove the TrayIcon, the `hide()` method does this. 

The `clear()` method instead clears the FXTrayIcon's menu. The javadoc should make this clear, though I admit the `clear()` method should probably be renamed to make this more clear. I will look into this for the next release.

**Comment by AmirAli-AZ** [comment] 2022-01-07 07:25
Yes, I also tried the `hide()` method that the program closes completely, but is there a way to not close the program?

**Comment by AmirAli-AZ** [comment] 2022-01-07 11:35
if 2 stage is showing and if we close the program by exit menu item 
this error will show :
`Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Key not associated with a running event loop: javafx.stage.Stage@62729689`
why this happen ?

**Comment by dustinkredmond** [comment] 2022-01-12 21:44
If you close the program via the Exit menu item, then JavaFX is closed via a call to `Platform.exit()`, thus subsequent calls to JavaFX API will throw the `IllegalArgumentException` that you're receiving, as JavaFX is no longer running. This is the intended behavior of the Exit menu item.

The `hide()`method, on the other hand simply removes the AWT TrayIcon from the SystemTray, JavaFX stays running. I'm not open to changing the implementation of the Exit menu item, as it is meant to exit the program (which it does).

If you have code that you could share in the form of a GitHub Gist, I'd be happy to review if I misunderstood your question. Thanks!

**Comment by AmirAli-AZ** [comment] 2022-01-14 12:19
I created a gist to show that error,
And how to fix it ?
https://gist.github.com/AmirAli-AZ/bbb5c874ba89be7ebf83019b5ae75b4f

**Comment by dustinkredmond** [comment] 2022-01-14 14:01
@AmirAli-AZ instead of calling the `showAndWait()` method on the second stage, call `show()`, then exit the application using the FXTrayIcon's exit item. No exceptions will be thrown.

**Closed by dustinkredmond** 2022-01-14 14:01 UTC
