### ISSUE TITLE
Icon looks blurred over time

### ISSUE THREAD

**Issue by hrzafer** [dustinkredmond/FXTrayIcon#33] opened 2021-12-16 18:50 UTC
Another issue I'm facing is this:

It looks OK at the start:

![image](https://user-images.githubusercontent.com/4048197/146430743-b4d375fa-bee1-46d1-9248-3e7622e63c82.png)

But after a while (maybe after a few hours, I don't know exactly), it looks like this or even worse sometimes: 

![image](https://user-images.githubusercontent.com/4048197/146430634-55a205e2-d436-46b1-9b06-ef7c9a57c25e.png)

I tried saving my icon both as `.gif` and `.png`. Neither worked.

**Comment by hrzafer** [comment] 2021-12-16 20:04
Interestingly, when user does something that triggers a notification message (`icon.showMessage(message)`), the icon is redrawn and looks OK again.

**Comment by EasyG0ing1** [comment] 2021-12-17 02:45
@hrzafer  That AWT stuff is crazy ... Some of the reading I did on it the other day had some suggestions of actually using a formal icon image in the .ico format ... you might try that, and also I would use an image that is at least double the required size of 16x16 (so make your image a 32x32) and then declare it explicitly in FXTIcon as a 16x16 image ... then mess with the image size ... try it for example at 20 x0 20 and see what happens ... 

Also, try that image I posted in the other issue ... it's a clean image and is larger than the one you're using. Having the software scale an image down is almost always best in these situations.

**Comment by dustinkredmond** [comment] 2021-12-20 17:44
Closing this issue as the advice offered by @EasyG0ing1 should mitigate this. This image quality degradation appears to be caused by the underlying AWT code instead of the FXTrayIcon abstraction.

If anyone finds evidence to the contrary, please feel free to create a new issue or re-open this.

**Closed by dustinkredmond** 2021-12-20 17:44 UTC
